/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uni.mapadventureproject.GUI;

import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jlTitolo = new javax.swing.JLabel();
        jbNuovo = new javax.swing.JButton();
        jbCarica = new javax.swing.JButton();
        jbEsci = new javax.swing.JButton();
        jlOscuro = new javax.swing.JLabel();
        jlLuce = new javax.swing.JLabel();
        jlVerde = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jmOpzioni = new javax.swing.JMenu();
        jmiNuovo = new javax.swing.JMenuItem();
        jmiCarica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAP ADVENTURE");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jpMenu.setLayout(null);

        jlTitolo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jlTitolo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitolo.setText("MAP ADVENTURE");
        jpMenu.add(jlTitolo);
        jlTitolo.setBounds(200, 20, 340, 40);

        jbNuovo.setBackground(new java.awt.Color(0, 102, 102));
        jbNuovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbNuovo.setForeground(new java.awt.Color(255, 255, 255));
        jbNuovo.setText("NUOVA PARTITA");
        jbNuovo.setToolTipText("Inizia una nuova avventura");
        jbNuovo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        jbNuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuovoActionPerformed(evt);
            }
        });
        jpMenu.add(jbNuovo);
        jbNuovo.setBounds(270, 130, 180, 30);

        jbCarica.setBackground(new java.awt.Color(0, 102, 102));
        jbCarica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCarica.setForeground(new java.awt.Color(255, 255, 255));
        jbCarica.setText("CARICA PARTITA");
        jbCarica.setToolTipText("Carica e continua una partita salvata");
        jbCarica.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        jbCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCaricaActionPerformed(evt);
            }
        });
        jpMenu.add(jbCarica);
        jbCarica.setBounds(270, 230, 180, 30);

        jbEsci.setBackground(new java.awt.Color(0, 102, 102));
        jbEsci.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbEsci.setForeground(new java.awt.Color(255, 255, 255));
        jbEsci.setText("ESCI");
        jbEsci.setToolTipText("Chiudi il gioco");
        jbEsci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        jbEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEsciActionPerformed(evt);
            }
        });
        jpMenu.add(jbEsci);
        jbEsci.setBounds(270, 350, 180, 30);

        jlOscuro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\MAPAdventure\\MAPAdventureProject\\img\\portale oscuro.png")); // NOI18N
        jpMenu.add(jlOscuro);
        jlOscuro.setBounds(0, 0, 350, 250);

        jlLuce.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\MAPAdventure\\MAPAdventureProject\\img\\portale luce.png")); // NOI18N
        jpMenu.add(jlLuce);
        jlLuce.setBounds(0, 250, 350, 230);

        jlVerde.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\MAPAdventure\\MAPAdventureProject\\img\\portale verde.png")); // NOI18N
        jpMenu.add(jlVerde);
        jlVerde.setBounds(350, -20, 350, 500);

        jMenuBar.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jmOpzioni.setText("Opzioni");

        jmiNuovo.setText("Nuova partita");
        jmiNuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuovoActionPerformed(evt);
            }
        });
        jmOpzioni.add(jmiNuovo);

        jmiCarica.setText("Carica partita");
        jmiCarica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCaricaActionPerformed(evt);
            }
        });
        jmOpzioni.add(jmiCarica);

        jMenuBar.add(jmOpzioni);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jmiNuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuovoActionPerformed
        //Game g=new Game();
        //Menu menu=new Menu(game g);
        // menu.newGame();
        GameGUI g = new GameGUI();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiNuovoActionPerformed

    private void jbEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEsciActionPerformed
        int option;
        option = JOptionPane.showConfirmDialog(this, "Sei sicuro di voler chiudere il gioco?", "Sei sicuro di voler chiudere il gioco", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbEsciActionPerformed

    private void jbNuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuovoActionPerformed

        //Game g=new Game();
        //Menu menu=new Menu(game g);
        // menu.newGame();
        GameGUI g = new GameGUI();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbNuovoActionPerformed

    private void jbCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCaricaActionPerformed
        //Game g=new Game();
        //Menu menu=new Menu(game g);
        // menu.loadGame();
        GameGUI g = new GameGUI();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbCaricaActionPerformed

    private void jmiCaricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCaricaActionPerformed
        //Game g=new Game();
        //Menu menu=new Menu(game g);
        // menu.loadGame();
        GameGUI g = new GameGUI();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiCaricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JButton jbCarica;
    private javax.swing.JButton jbEsci;
    private javax.swing.JButton jbNuovo;
    private javax.swing.JLabel jlLuce;
    private javax.swing.JLabel jlOscuro;
    private javax.swing.JLabel jlTitolo;
    private javax.swing.JLabel jlVerde;
    private javax.swing.JMenu jmOpzioni;
    private javax.swing.JMenuItem jmiCarica;
    private javax.swing.JMenuItem jmiNuovo;
    private javax.swing.JPanel jpMenu;
    // End of variables declaration//GEN-END:variables
}
